### ISSUE TITLE
The cookbook is no longer compatible with Chef 13, 14 – value_for_platform_family is not available in resources

### ISSUE THREAD

**Issue by sebastianriese** [sous-chefs/keepalived#103]
## :ghost: Brief Description

When running the kitchen tests with Chef 13 or Chef 14 they fail with an undefined method error. The call was introduced between v4.0.0 and v5.0.0. Chef 14 is not yet EOL and the cookbook metadata still claims compatibility with Chef 13. So this should be fixed.

A lot of organizations use chef client versions beyond their EOL.

## :pancakes: Cookbook version

v5.0.0

## :woman_cook:  Chef-Infra Version

14.13.11 (or earlier)

## :tophat: Platform details

kitchen tests with dokken and the bento/ubuntu-1804 image.

## Steps To Reproduce

1. Run the kitchen tests with the appropriate environment: `CHEF_VERSION=15 KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen converge default-ubuntu-1804`
2. The converge fails with the following errors:
```
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/keepalived/resources/install.rb
================================================================================

NoMethodError
-------------
undefined method `value_for_platform_family' for #<Class:0x0000000003a5d450>

Cookbook Trace:
---------------
  /opt/kitchen/cache/cookbooks/keepalived/resources/install.rb:6:in `class_from_file'

Relevant File Content:
----------------------
/opt/kitchen/cache/cookbooks/keepalived/resources/install.rb:

  1:  property :package_name, String, default: 'keepalived'
  2:  property :root_path,    String, default: '/etc/keepalived'
  3:  property :config_path,  String, default: lazy { "#{root_path}/conf.d" }
  4:  property :server_path,  String, default: lazy { "#{root_path}/servers.d" }
  5:  property :health_path,  String, default: lazy { "#{root_path}/checks.d" }
  6>> property :defaults_path, String, default: value_for_platform_family(
  7:                                              debian: '/etc/default/keepalived',
  8:                                              default: '/etc/sysconfig/keepalived'
  9:                                            )
 10:  action :install do
 11:    package new_resource.package_name
 12:  
 13:    [
 14:      new_resource.config_path,
 15:      new_resource.server_path,

System Info:
------------
chef_version=14.13.11
platform=ubuntu
platform_version=18.04
ruby=ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
program_name=/opt/chef/embedded/bin/chef-client
executable=/opt/chef/embedded/bin/chef-client
```
## :police_car: Expected behavior

The converge is successful.

## :heavy_plus_sign: Additional context

I found this issue while trying to test my changes to fix #74. My organization still uses Chef 14, so I needed to test that it works.

I don't quite get why it does not work, since the method is in the `Chef::DSL::Universal` module, that has for a long time been included everywhere.

**Comment by Xorima** [comment]
This is resolved in `5.0.1`
