### ISSUE TITLE
keepalived_vrrp_instance has required properties that should not be required

### ISSUE THREAD

**Issue by sebastianriese** [sous-chefs/keepalived#74]
## :ghost: Brief Description

The properties `authentication` and `virtual_router_id` of the `keepalived_vrrp_instance` resource are required, but should not be, as they are simply ignored when deleting instances.

Apart from that, requiring authentication is a really bad idea. Authentication in VRRP has been deprecated for use with VRRPv2 since 2004 (!) <https://tools.ietf.org/html/rfc3768#section-10>, and is not defined at all in VRRPv3 – so VRRPv3 instances created with this cookbook lead to a warning with keepalived (saying that the authentication configuration is ignored).

The validation that a `virtual_router_id` is set would have to be delayed to the `:create` action, while this unfortunately leads to run-time failures, there is no remedy if a convenient `:delete` action shall be supported.

If you agree with my proposal I would be happy to make a PR fixing the issue.

## :pancakes: Cookbook version

all up to 3.1.1

## :woman_cook:  Chef-Infra Version

14.8.12 (irrelevant for the issue)

## :tophat: Platform details

Ubuntu 18.04 (mostly irrelevant for the issue)

## Steps To Reproduce

1. Try to create a VRRPv3 instance, you have to specify authentication, and keepalived will emit a warning due to ignored configuration
    ```
   keepalive_vrrp_instance 'instance_v3' do
      # ... other configuration ...
      version 3
      authentication(
       auth_type: 'PASS',
       auth_pass: 'fnord'
     )
   end
    ```

2. Try to delete a VRRP instance, you will have to write

   ```
   keepalived_vrrp_instance 'instance_name' do
     action :delete

     # these are just workarounds for the keepalived cookbook's
     # creative use of required options
     virtual_router_id 0
     authentication(
       auth_type: 'PASS',
       auth_pass: 'fnord'
     )
   end
   ```

## :police_car: Expected behavior

1. It should be possible to create valid configuration for VRRPv3

   ```
   keealived_vrrp_instance 'instance_v3' do
      version 3
      # ... other configuration, but *not* authentication block     
   end
   ```

2. It should be possible to delete a VRRP instance by just saying

   ```
   keepalived_vrrp_instance 'instance_name' do
       action :delete
   end
   ```

**Comment by Xorima** [comment]
Hi @sebastianriese 

If you could make a PR for the `authentication` property to not be required that would be great.

The `virtual_router_id` while annoying I cannot see a way around it, so for now please leave that as required.

**Comment by sebastianriese** [comment]
I think the problem with `virtual_router_id` is solved with your rewrite in the custom resources scheme. If I remember correctly a required property does only error in the new framework, when it is actually accessed in an action. Since the delete action does not access the `virtual_router_id` this should have the desired behaviour now. I will verify that and make a PR regarding the authentication.

**Comment by sebastianriese** [comment]
I've added an instance deletion to the kitchen, and it works without giving it a `virtual_router_id`. So that part of the issue is already addressed.
