### ISSUE TITLE
Mark recipes as deprecated

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/keepalived#84]
## :ghost: Brief Description

We will be getting rid of recipes in the next major release, we should add a log resource of level warn to each recipe at the end saying that recipes will be deprecated in the next release and to move onto available resources

Note: We should also update the documentation for things we are not going to be managing, such as the service resource, this should be done with notifies from the correct resources etc

## :pancakes: Cookbook version

current master

## :police_car: Expected behavior

Chef logs a warning

**Comment by thirumoorthir** [comment]
I like to do this

**Comment by Xorima** [comment]
Closed by #90
