### ISSUE TITLE
not able to install keepalived

### ISSUE THREAD

**Issue by gangadhar01a** [sous-chefs/keepalived#86]
## :ghost: Brief Description
I am trying to use keepalived cookbook to install on centos 7 machine, I have included the dependency in metadata.rb file. When I ran the chef-client it resulted in undefined local variable or method. I am using the latest chef client (15.4.45)

Undefined local variable or method `keepalived' for cookbook: nrhl_haproxy, recipe: keepalived :Chef::Recipe

keepalived.rb:
1>> keepalived::install

Keepalived version: 3.1.1
OS: centos7
chef-client: 15.4.45

**Comment by nathwill** [comment]
i think you want to `include_recipe "keepalived::install"
